.PHONY: clean All

All:
	@echo "----------Building project:[ fourPointTwo - Debug ]----------"
	@cd "fourPointTwo" && "$(MAKE)" -f  "fourPointTwo.mk" && "$(MAKE)" -f  "fourPointTwo.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ fourPointTwo - Debug ]----------"
	@cd "fourPointTwo" && "$(MAKE)" -f  "fourPointTwo.mk" clean
