.PHONY: clean All

All:
	@echo "----------Building project:[ olofskeypad - Debug ]----------"
	@cd "olofskeypad" && "$(MAKE)" -f  "olofskeypad.mk" && "$(MAKE)" -f  "olofskeypad.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ olofskeypad - Debug ]----------"
	@cd "olofskeypad" && "$(MAKE)" -f  "olofskeypad.mk" clean
