.PHONY: clean All

All:
	@echo "----------Building project:[ fivePointThree - Debug ]----------"
	@cd "fivePointThree" && "$(MAKE)" -f  "fivePointThree.mk" && "$(MAKE)" -f  "fivePointThree.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ fivePointThree - Debug ]----------"
	@cd "fivePointThree" && "$(MAKE)" -f  "fivePointThree.mk" clean
