.PHONY: clean All

All:
	@echo "----------Building project:[ uppg910 - Debug ]----------"
	@cd "uppg10" && "$(MAKE)" -f  "uppg910.mk" && "$(MAKE)" -f  "uppg910.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ uppg910 - Debug ]----------"
	@cd "uppg10" && "$(MAKE)" -f  "uppg910.mk" clean
