.PHONY: clean All

All:
	@echo "----------Building project:[ MinecraftRippoff - Debug ]----------"
	@cd "MinecraftRippoff" && "$(MAKE)" -f  "MinecraftRippoff.mk"
clean:
	@echo "----------Cleaning project:[ MinecraftRippoff - Debug ]----------"
	@cd "MinecraftRippoff" && "$(MAKE)" -f  "MinecraftRippoff.mk" clean
