@startuml

title __LABB-1's Class Diagram__\n

  namespace  {
    namespace abb {
      class Labb.AngledFlatbed {
      }
    }
  }
  

  namespace  {
    namespace abb {
      abstract class Labb.Car {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.CarController {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.CarFerry {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.CarTransporter {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.CarView {
      }
    }
  }
  

  namespace  {
    namespace abb {
      enum Direction {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.DrawPanel {
      }
    }
  }
  

  namespace  {
    namespace abb {
      abstract class Labb.Flatbed {
      }
    }
  }
  

  namespace  {
    namespace abb {
      interface Labb.ICanLoadCars {
      }
    }
  }
  

  namespace  {
    namespace abb {
      interface Labb.IMovable {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.Main {
      }
    }
  }
  

  namespace  {
    namespace abb {
      abstract class Labb.MotorizedVehicle {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.Saab95 {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.Scania {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.StateFlatbed {
      }
    }
  }
  

  namespace  {
    namespace abb {
      abstract class Labb.Truck {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.Volvo240 {
      }
    }
  }
  

  namespace  {
    namespace abb {
      class Labb.Workshop {
      }
    }
  }
  

  Labb.AngledFlatbed -up-|> Labb.Flatbed
  Labb.Car -up-|> Labb.MotorizedVehicle
  Labb.CarController o-- Labb.CarView : frame
  Labb.CarFerry .up.|> Labb.ICanLoadCars
  Labb.CarFerry -up-|> Labb.MotorizedVehicle
  Labb.CarTransporter .up.|> Labb.ICanLoadCars
  Labb.CarTransporter -up-|> Labb.Truck
  Labb.CarView -up-|> javax.swing.JFrame
  Labb.CarView o-- Labb.CarController : carC
  Labb.CarView o-- Labb.DrawPanel : drawPanel
  Labb.DrawPanel -up-|> javax.swing.JPanel
  Labb.MotorizedVehicle .up.|> Labb.IMovable
  Labb.MotorizedVehicle o-- Labb.ICanLoadCars : carrier
  Labb.MotorizedVehicle o-- Labb.Direction : currentDirection
  Labb.Saab95 -up-|> Labb.Car
  Labb.Scania -up-|> Labb.Truck
  Labb.Scania o-- Labb.Flatbed : flatbed
  Labb.StateFlatbed -up-|> Labb.Flatbed
  Labb.Truck -up-|> Labb.MotorizedVehicle
  Labb.Volvo240 -up-|> Labb.Car
  Labb.Workshop .up.|> Labb.ICanLoadCars


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
