.PHONY: clean All

All:
	@echo "----------Building project:[ uppg5 - Debug ]----------"
	@cd "uppg5" && "$(MAKE)" -f  "uppg5.mk" && "$(MAKE)" -f  "uppg5.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ uppg5 - Debug ]----------"
	@cd "uppg5" && "$(MAKE)" -f  "uppg5.mk" clean
